name: DR_PETS
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - ca-certificates=2025.4.26
  - decorator=5.1.1
  - entrypoints=0.4
  - ipykernel=5.5.5
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.5.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgomp=13.1.0
  - libnsl=2.0.0
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=1.1.1w
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prompt_toolkit=1.0.15
  - ptyprocess=0.7.0
  - pygments=2.12.0
  - python=3.6.15
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pyzmq=19.0.2
  - readline=8.2
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - sqlite=3.42.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - wcwidth=0.2.6
  - wheel=0.36.2
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - astor==0.8.1
    - attrs==22.1.0
    - cached-property==1.5.2
    - certifi==2023.7.22
    - charset-normalizer==2.0.12
    - cloudpickle==2.2.1
    - dotmap==1.2.20
    - future==0.16.0
    - gast==0.5.3
    - gpflow==1.1.0
    - grpcio==1.48.2
    - gym==0.9.4
    - gymgrid2==1.2.6
    - gymnasium==0.26.3
    - gymnasium-notices==0.0.1
    - h5py==3.1.0
    - idna==3.4
    - iniconfig==1.1.1
    - joblib==1.1.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.7
    - mujoco-py==0.5.7
    - multipledispatch==0.6.0
    - numpy==1.18.0
    - pandas==1.0.5
    - pluggy==1.0.0
    - protobuf==3.19.6
    - py==1.11.0
    - pyglet==1.5.27
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - pytest==7.0.1
    - pytz==2022.6
    - requests==2.27.1
    - scikit-learn==0.21.3
    - scipy==0.19.0
    - tensorboard==1.12.2
    - tensorflow-gpu==1.12.0
    - termcolor==1.1.0
    - tomli==1.2.3
    - tqdm==4.19.4
    - urllib3==1.26.12
    - werkzeug==2.0.3
